"""Database seeding with sample questions.

SRP: Only handles seeding sample data into the database.
"""

from src.database import SessionLocal
from src.logger import get_logger

logger = get_logger(__name__)


def seed_questions() -> None:
    """Seed the database with sample questions."""
    from src.models.question import Question

    sample_questions = [
        # === COUNTRIES - EASY ===
        Question(
            text="Where is France located?",
            location_type="country",
            latitude=46.603354,
            longitude=1.888334,
            difficulty="easy",
            hint="Western Europe",
            time_limit=60,
            category="countries",
        ),
        Question(
            text="Find Brazil on the map",
            location_type="country",
            latitude=-14.2350,
            longitude=-51.9253,
            difficulty="easy",
            hint="South America",
            time_limit=60,
            category="countries",
        ),
        Question(
            text="Where is Australia?",
            location_type="country",
            latitude=-25.2744,
            longitude=133.7751,
            difficulty="easy",
            hint="Southern Hemisphere",
            time_limit=60,
            category="countries",
        ),
        Question(
            text="Where is the United States of America?",
            location_type="country",
            latitude=37.0902,
            longitude=-95.7129,
            difficulty="easy",
            hint="North America",
            time_limit=60,
            category="countries",
        ),
        Question(
            text="Find Canada on the map",
            location_type="country",
            latitude=56.1304,
            longitude=-106.3468,
            difficulty="easy",
            hint="North of the USA",
            time_limit=60,
            category="countries",
        ),
        Question(
            text="Where is Russia?",
            location_type="country",
            latitude=61.5240,
            longitude=105.3188,
            difficulty="easy",
            hint="Largest country in the world",
            time_limit=60,
            category="countries",
        ),
        Question(
            text="Find India on the map",
            location_type="country",
            latitude=20.5937,
            longitude=78.9629,
            difficulty="easy",
            hint="South Asia",
            time_limit=60,
            category="countries",
        ),
        Question(
            text="Where is China?",
            location_type="country",
            latitude=35.8617,
            longitude=104.1954,
            difficulty="easy",
            hint="Eastern Asia",
            time_limit=60,
            category="countries",
        ),
        # === COUNTRIES - MEDIUM ===
        Question(
            text="Find Egypt on the map",
            location_type="country",
            latitude=26.8206,
            longitude=30.8025,
            difficulty="medium",
            hint="Northeastern Africa",
            time_limit=45,
            category="countries",
        ),
        Question(
            text="Where is Argentina?",
            location_type="country",
            latitude=-38.4161,
            longitude=-63.6167,
            difficulty="medium",
            hint="Southern South America",
            time_limit=45,
            category="countries",
        ),
        Question(
            text="Find Saudi Arabia on the map",
            location_type="country",
            latitude=23.8859,
            longitude=45.0792,
            difficulty="medium",
            hint="Middle East",
            time_limit=45,
            category="countries",
        ),
        Question(
            text="Where is South Africa?",
            location_type="country",
            latitude=-30.5595,
            longitude=22.9375,
            difficulty="medium",
            hint="Southern tip of Africa",
            time_limit=45,
            category="countries",
        ),
        Question(
            text="Find Indonesia on the map",
            location_type="country",
            latitude=-0.7893,
            longitude=113.9213,
            difficulty="medium",
            hint="Southeast Asia archipelago",
            time_limit=45,
            category="countries",
        ),
        Question(
            text="Where is Mexico?",
            location_type="country",
            latitude=23.6345,
            longitude=-102.5528,
            difficulty="medium",
            hint="North America, south of the USA",
            time_limit=45,
            category="countries",
        ),
        Question(
            text="Find Turkey on the map",
            location_type="country",
            latitude=38.9637,
            longitude=35.2433,
            difficulty="medium",
            hint="Between Europe and Asia",
            time_limit=45,
            category="countries",
        ),
        Question(
            text="Where is Spain?",
            location_type="country",
            latitude=40.4637,
            longitude=-3.7492,
            difficulty="medium",
            hint="Southwestern Europe",
            time_limit=45,
            category="countries",
        ),
        # === COUNTRIES - HARD ===
        Question(
            text="Find Kazakhstan on the map",
            location_type="country",
            latitude=48.0196,
            longitude=66.9237,
            difficulty="hard",
            hint="Central Asia",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Where is Papua New Guinea?",
            location_type="country",
            latitude=-6.3150,
            longitude=143.9555,
            difficulty="hard",
            hint="North of Australia",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Find Chile on the map",
            location_type="country",
            latitude=-35.6751,
            longitude=-71.5430,
            difficulty="hard",
            hint="Long narrow country in South America",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Where is Madagascar?",
            location_type="country",
            latitude=-18.7669,
            longitude=46.8691,
            difficulty="hard",
            hint="Island nation off the coast of Africa",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Find Iceland on the map",
            location_type="country",
            latitude=64.9631,
            longitude=-19.0208,
            difficulty="hard",
            hint="North Atlantic island nation",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Where is New Zealand?",
            location_type="country",
            latitude=-40.9006,
            longitude=174.8860,
            difficulty="hard",
            hint="Southwest Pacific Ocean",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Find Norway on the map",
            location_type="country",
            latitude=60.4720,
            longitude=8.4689,
            difficulty="medium",
            hint="Scandinavian country in Northern Europe",
            time_limit=45,
            category="countries",
        ),
        Question(
            text="Where is Sweden?",
            location_type="country",
            latitude=60.1282,
            longitude=18.6435,
            difficulty="medium",
            hint="Scandinavian country, east of Norway",
            time_limit=45,
            category="countries",
        ),
        Question(
            text="Find Finland on the map",
            location_type="country",
            latitude=61.9241,
            longitude=25.7482,
            difficulty="medium",
            hint="Nordic country, land of a thousand lakes",
            time_limit=45,
            category="countries",
        ),
        Question(
            text="Where is Poland?",
            location_type="country",
            latitude=51.9194,
            longitude=19.1451,
            difficulty="medium",
            hint="Central Europe, east of Germany",
            time_limit=45,
            category="countries",
        ),
        Question(
            text="Find Ukraine on the map",
            location_type="country",
            latitude=48.3794,
            longitude=31.1656,
            difficulty="medium",
            hint="Eastern Europe, largest country entirely in Europe",
            time_limit=45,
            category="countries",
        ),
        Question(
            text="Where is Greece?",
            location_type="country",
            latitude=39.0742,
            longitude=21.8243,
            difficulty="medium",
            hint="Southern Europe, birthplace of democracy",
            time_limit=45,
            category="countries",
        ),
        Question(
            text="Find Portugal on the map",
            location_type="country",
            latitude=39.3999,
            longitude=-8.2245,
            difficulty="medium",
            hint="Southwestern Europe, west of Spain",
            time_limit=45,
            category="countries",
        ),
        Question(
            text="Where is the Netherlands?",
            location_type="country",
            latitude=52.1326,
            longitude=5.2913,
            difficulty="medium",
            hint="Low Countries, famous for tulips and windmills",
            time_limit=45,
            category="countries",
        ),
        Question(
            text="Find Switzerland on the map",
            location_type="country",
            latitude=46.8182,
            longitude=8.2275,
            difficulty="medium",
            hint="Central European country, famous for Alps",
            time_limit=45,
            category="countries",
        ),
        Question(
            text="Where is Austria?",
            location_type="country",
            latitude=47.5162,
            longitude=14.5501,
            difficulty="medium",
            hint="Central Europe, north of Italy",
            time_limit=45,
            category="countries",
        ),
        Question(
            text="Find Belgium on the map",
            location_type="country",
            latitude=50.5039,
            longitude=4.4699,
            difficulty="medium",
            hint="Western Europe, between France and Netherlands",
            time_limit=45,
            category="countries",
        ),
        Question(
            text="Where is Ireland?",
            location_type="country",
            latitude=53.1424,
            longitude=-7.6921,
            difficulty="medium",
            hint="Island nation west of Great Britain",
            time_limit=45,
            category="countries",
        ),
        Question(
            text="Find Denmark on the map",
            location_type="country",
            latitude=56.2639,
            longitude=9.5018,
            difficulty="medium",
            hint="Scandinavian country, southernmost of the Nordic countries",
            time_limit=45,
            category="countries",
        ),
        Question(
            text="Where is Morocco?",
            location_type="country",
            latitude=31.7917,
            longitude=-7.0926,
            difficulty="hard",
            hint="Northwestern Africa, across from Spain",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Find Ethiopia on the map",
            location_type="country",
            latitude=9.1450,
            longitude=40.4897,
            difficulty="hard",
            hint="Horn of Africa, oldest independent nation in Africa",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Where is Kenya?",
            location_type="country",
            latitude=-0.0236,
            longitude=37.9062,
            difficulty="hard",
            hint="East Africa, famous for safaris",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Find Nigeria on the map",
            location_type="country",
            latitude=9.0820,
            longitude=8.6753,
            difficulty="hard",
            hint="West Africa, most populous African nation",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Where is Peru?",
            location_type="country",
            latitude=-9.1900,
            longitude=-75.0152,
            difficulty="hard",
            hint="Western South America, home of Machu Picchu",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Find Colombia on the map",
            location_type="country",
            latitude=4.5709,
            longitude=-74.2973,
            difficulty="hard",
            hint="Northwestern South America, gateway to South America",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Where is Venezuela?",
            location_type="country",
            latitude=6.4238,
            longitude=-66.5897,
            difficulty="hard",
            hint="Northern South America, Caribbean coast",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Find Ecuador on the map",
            location_type="country",
            latitude=-1.8312,
            longitude=-78.1834,
            difficulty="hard",
            hint="Equatorial South America, named after the equator",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Where is Uruguay?",
            location_type="country",
            latitude=-32.5228,
            longitude=-55.7658,
            difficulty="hard",
            hint="Southeastern South America, between Brazil and Argentina",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Find Paraguay on the map",
            location_type="country",
            latitude=-23.4425,
            longitude=-58.4438,
            difficulty="hard",
            hint="Landlocked country in South America",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Where is Bolivia?",
            location_type="country",
            latitude=-16.2902,
            longitude=-63.5887,
            difficulty="hard",
            hint="Central South America, named after Simón Bolívar",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Find Nepal on the map",
            location_type="country",
            latitude=28.3949,
            longitude=84.1240,
            difficulty="hard",
            hint="Himalayan country, home to Mount Everest",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Where is Bangladesh?",
            location_type="country",
            latitude=23.6850,
            longitude=90.3563,
            difficulty="hard",
            hint="South Asia, east of India",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Find Pakistan on the map",
            location_type="country",
            latitude=30.3753,
            longitude=69.3451,
            difficulty="hard",
            hint="South Asia, west of India",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Where is Afghanistan?",
            location_type="country",
            latitude=33.9391,
            longitude=67.7100,
            difficulty="hard",
            hint="Central/South Asia, land of the Afghans",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Find Iraq on the map",
            location_type="country",
            latitude=33.2232,
            longitude=43.6793,
            difficulty="hard",
            hint="Middle East, ancient Mesopotamia",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Where is Iran?",
            location_type="country",
            latitude=32.4279,
            longitude=53.6880,
            difficulty="hard",
            hint="Middle East, formerly known as Persia",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Find Syria on the map",
            location_type="country",
            latitude=34.8021,
            longitude=38.9968,
            difficulty="hard",
            hint="Middle East, eastern Mediterranean",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Where is Israel?",
            location_type="country",
            latitude=31.0461,
            longitude=34.8516,
            difficulty="hard",
            hint="Middle East, eastern Mediterranean coast",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Find Jordan on the map",
            location_type="country",
            latitude=30.5852,
            longitude=36.2384,
            difficulty="hard",
            hint="Middle East, east of Israel",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Where is Lebanon?",
            location_type="country",
            latitude=33.8547,
            longitude=35.8623,
            difficulty="hard",
            hint="Middle East, smallest country in the Arab world",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Find Kuwait on the map",
            location_type="country",
            latitude=29.3117,
            longitude=47.4818,
            difficulty="hard",
            hint="Middle East, Persian Gulf",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Where is the United Arab Emirates?",
            location_type="country",
            latitude=23.4241,
            longitude=53.8478,
            difficulty="hard",
            hint="Middle East, Persian Gulf, known for Dubai",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Find Qatar on the map",
            location_type="country",
            latitude=25.3548,
            longitude=51.1839,
            difficulty="hard",
            hint="Middle East, small peninsula in the Persian Gulf",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Where is Oman?",
            location_type="country",
            latitude=21.4735,
            longitude=55.9754,
            difficulty="hard",
            hint="Arabian Peninsula, southeastern coast",
            time_limit=30,
            category="countries",
        ),
        Question(
            text="Find Yemen on the map",
            location_type="country",
            latitude=15.5527,
            longitude=48.5164,
            difficulty="hard",
            hint="Southern Arabian Peninsula",
            time_limit=30,
            category="countries",
        ),
        # === CITIES - EASY ===
        Question(
            text="Where is London, United Kingdom?",
            location_type="city",
            latitude=51.5074,
            longitude=-0.1278,
            difficulty="easy",
            hint="Capital of the UK",
            time_limit=60,
            category="cities",
        ),
        Question(
            text="Find New York City on the map",
            location_type="city",
            latitude=40.7128,
            longitude=-74.0060,
            difficulty="easy",
            hint="East Coast, USA",
            time_limit=60,
            category="cities",
        ),
        Question(
            text="Where is Paris, France?",
            location_type="city",
            latitude=48.8566,
            longitude=2.3522,
            difficulty="easy",
            hint="City of Light",
            time_limit=60,
            category="cities",
        ),
        Question(
            text="Find Rome, Italy on the map",
            location_type="city",
            latitude=41.9028,
            longitude=12.4964,
            difficulty="easy",
            hint="The Eternal City",
            time_limit=60,
            category="cities",
        ),
        # === CITIES - MEDIUM ===
        Question(
            text="Where is Tokyo, Japan?",
            location_type="city",
            latitude=35.6762,
            longitude=139.6503,
            difficulty="medium",
            hint="Capital of Japan",
            time_limit=45,
            category="cities",
        ),
        Question(
            text="Find Berlin, Germany on the map",
            location_type="city",
            latitude=52.5200,
            longitude=13.4050,
            difficulty="medium",
            hint="Capital of Germany",
            time_limit=45,
            category="cities",
        ),
        Question(
            text="Where is Moscow, Russia?",
            location_type="city",
            latitude=55.7558,
            longitude=37.6173,
            difficulty="medium",
            hint="Capital of Russia",
            time_limit=45,
            category="cities",
        ),
        Question(
            text="Find Sydney, Australia on the map",
            location_type="city",
            latitude=-33.8688,
            longitude=151.2093,
            difficulty="medium",
            hint="Largest city in Australia",
            time_limit=45,
            category="cities",
        ),
        Question(
            text="Where is Cairo, Egypt?",
            location_type="city",
            latitude=30.0444,
            longitude=31.2357,
            difficulty="medium",
            hint="Capital of Egypt",
            time_limit=45,
            category="cities",
        ),
        Question(
            text="Find Buenos Aires, Argentina on the map",
            location_type="city",
            latitude=-34.6037,
            longitude=-58.3816,
            difficulty="medium",
            hint="Capital of Argentina",
            time_limit=45,
            category="cities",
        ),
        Question(
            text="Where is Bangkok, Thailand?",
            location_type="city",
            latitude=13.7563,
            longitude=100.5018,
            difficulty="medium",
            hint="Capital of Thailand",
            time_limit=45,
            category="cities",
        ),
        Question(
            text="Find Istanbul, Turkey on the map",
            location_type="city",
            latitude=41.0082,
            longitude=28.9784,
            difficulty="medium",
            hint="Largest city in Turkey",
            time_limit=45,
            category="cities",
        ),
        # === CITIES - HARD ===
        Question(
            text="Where is Reykjavik, Iceland?",
            location_type="city",
            latitude=64.1466,
            longitude=-21.9426,
            difficulty="hard",
            hint="Northernmost capital in the world",
            time_limit=30,
            category="cities",
        ),
        Question(
            text="Find Kathmandu, Nepal on the map",
            location_type="city",
            latitude=27.7172,
            longitude=85.3240,
            difficulty="hard",
            hint="Capital of Nepal",
            time_limit=30,
            category="cities",
        ),
        Question(
            text="Where is Nairobi, Kenya?",
            location_type="city",
            latitude=-1.2921,
            longitude=36.8219,
            difficulty="hard",
            hint="Capital of Kenya",
            time_limit=30,
            category="cities",
        ),
        Question(
            text="Find Ulaanbaatar, Mongolia on the map",
            location_type="city",
            latitude=47.8864,
            longitude=106.9057,
            difficulty="hard",
            hint="Capital of Mongolia",
            time_limit=30,
            category="cities",
        ),
        Question(
            text="Where is Wellington, New Zealand?",
            location_type="city",
            latitude=-41.2865,
            longitude=174.7762,
            difficulty="hard",
            hint="Southernmost capital in the world",
            time_limit=30,
            category="cities",
        ),
        # === LANDMARKS - EASY ===
        Question(
            text="Where is the Eiffel Tower?",
            location_type="landmark",
            latitude=48.8584,
            longitude=2.2945,
            difficulty="easy",
            hint="Paris, France",
            time_limit=60,
            category="landmarks",
        ),
        Question(
            text="Find the Statue of Liberty on the map",
            location_type="landmark",
            latitude=40.6892,
            longitude=-74.0445,
            difficulty="easy",
            hint="New York Harbor, USA",
            time_limit=60,
            category="landmarks",
        ),
        Question(
            text="Where is the Great Pyramid of Giza?",
            location_type="landmark",
            latitude=29.9792,
            longitude=31.1342,
            difficulty="easy",
            hint="Near Cairo, Egypt",
            time_limit=60,
            category="landmarks",
        ),
        Question(
            text="Find the Colosseum on the map",
            location_type="landmark",
            latitude=41.8902,
            longitude=12.4922,
            difficulty="easy",
            hint="Rome, Italy",
            time_limit=60,
            category="landmarks",
        ),
        Question(
            text="Where is the Taj Mahal?",
            location_type="landmark",
            latitude=27.1751,
            longitude=78.0421,
            difficulty="easy",
            hint="Agra, India",
            time_limit=60,
            category="landmarks",
        ),
        # === LANDMARKS - MEDIUM ===
        Question(
            text="Find the Great Wall of China on the map",
            location_type="landmark",
            latitude=40.4319,
            longitude=116.5704,
            difficulty="medium",
            hint="Northern China",
            time_limit=45,
            category="landmarks",
        ),
        Question(
            text="Where is Machu Picchu?",
            location_type="landmark",
            latitude=-13.1631,
            longitude=-72.5450,
            difficulty="medium",
            hint="Ancient Inca city in Peru",
            time_limit=45,
            category="landmarks",
        ),
        Question(
            text="Find the Sydney Opera House on the map",
            location_type="landmark",
            latitude=-33.8568,
            longitude=151.2153,
            difficulty="medium",
            hint="Sydney, Australia",
            time_limit=45,
            category="landmarks",
        ),
        Question(
            text="Where is Stonehenge?",
            location_type="landmark",
            latitude=51.1789,
            longitude=-1.8262,
            difficulty="medium",
            hint="England, UK",
            time_limit=45,
            category="landmarks",
        ),
        Question(
            text="Find the Christ the Redeemer statue on the map",
            location_type="landmark",
            latitude=-22.9519,
            longitude=-43.2105,
            difficulty="medium",
            hint="Rio de Janeiro, Brazil",
            time_limit=45,
            category="landmarks",
        ),
        Question(
            text="Where is the Leaning Tower of Pisa?",
            location_type="landmark",
            latitude=43.7230,
            longitude=10.3966,
            difficulty="medium",
            hint="Italy",
            time_limit=45,
            category="landmarks",
        ),
        Question(
            text="Find the Brandenburg Gate on the map",
            location_type="landmark",
            latitude=52.5163,
            longitude=13.3777,
            difficulty="medium",
            hint="Berlin, Germany",
            time_limit=45,
            category="landmarks",
        ),
        Question(
            text="Where is Angkor Wat?",
            location_type="landmark",
            latitude=13.4125,
            longitude=103.8670,
            difficulty="medium",
            hint="Cambodia",
            time_limit=45,
            category="landmarks",
        ),
        # === LANDMARKS - HARD ===
        Question(
            text="Find Petra on the map",
            location_type="landmark",
            latitude=30.3285,
            longitude=35.4444,
            difficulty="hard",
            hint="Ancient city in Jordan",
            time_limit=30,
            category="landmarks",
        ),
        Question(
            text="Where is Mount Fuji?",
            location_type="landmark",
            latitude=35.3606,
            longitude=138.7274,
            difficulty="hard",
            hint="Highest mountain in Japan",
            time_limit=30,
            category="landmarks",
        ),
        Question(
            text="Find the Galapagos Islands on the map",
            location_type="landmark",
            latitude=-0.9538,
            longitude=-90.9656,
            difficulty="hard",
            hint="Pacific Ocean, near Ecuador",
            time_limit=30,
            category="landmarks",
        ),
        Question(
            text="Where is Uluru (Ayers Rock)?",
            location_type="landmark",
            latitude=-25.3444,
            longitude=131.0369,
            difficulty="hard",
            hint="Central Australia",
            time_limit=30,
            category="landmarks",
        ),
        Question(
            text="Find the Moai statues on the map",
            location_type="landmark",
            latitude=-27.1127,
            longitude=-109.3497,
            difficulty="hard",
            hint="Easter Island, Chile",
            time_limit=30,
            category="landmarks",
        ),
        Question(
            text="Where is the Matterhorn?",
            location_type="landmark",
            latitude=45.9763,
            longitude=7.6586,
            difficulty="hard",
            hint="Swiss Alps",
            time_limit=30,
            category="landmarks",
        ),
        Question(
            text="Find Borobudur on the map",
            location_type="landmark",
            latitude=-7.6079,
            longitude=110.2038,
            difficulty="hard",
            hint="Buddhist temple in Indonesia",
            time_limit=30,
            category="landmarks",
        ),
        Question(
            text="Where is Victoria Falls?",
            location_type="landmark",
            latitude=-17.9243,
            longitude=25.8572,
            difficulty="hard",
            hint="Border of Zambia and Zimbabwe",
            time_limit=30,
            category="landmarks",
        ),
        # === CAPITALS - EASY ===
        Question(
            text="Where is Paris, the capital of France?",
            location_type="city",
            latitude=48.8566,
            longitude=2.3522,
            difficulty="easy",
            hint="Western Europe",
            time_limit=60,
            category="capitals",
        ),
        Question(
            text="Find London, capital of the United Kingdom",
            location_type="city",
            latitude=51.5074,
            longitude=-0.1278,
            difficulty="easy",
            hint="Western Europe, on the Thames River",
            time_limit=60,
            category="capitals",
        ),
        Question(
            text="Where is Rome, capital of Italy?",
            location_type="city",
            latitude=41.9028,
            longitude=12.4964,
            difficulty="easy",
            hint="Southern Europe, the Eternal City",
            time_limit=60,
            category="capitals",
        ),
        Question(
            text="Find Berlin, capital of Germany",
            location_type="city",
            latitude=52.5200,
            longitude=13.4050,
            difficulty="easy",
            hint="Central Europe",
            time_limit=60,
            category="capitals",
        ),
        Question(
            text="Where is Madrid, capital of Spain?",
            location_type="city",
            latitude=40.4168,
            longitude=-3.7038,
            difficulty="easy",
            hint="Southwestern Europe, Iberian Peninsula",
            time_limit=60,
            category="capitals",
        ),
        Question(
            text="Find Moscow, capital of Russia",
            location_type="city",
            latitude=55.7558,
            longitude=37.6173,
            difficulty="easy",
            hint="Eastern Europe, largest city in Europe",
            time_limit=60,
            category="capitals",
        ),
        # === CAPITALS - MEDIUM ===
        Question(
            text="Find Tokyo, capital of Japan",
            location_type="city",
            latitude=35.6762,
            longitude=139.6503,
            difficulty="medium",
            hint="East Asia",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Where is Washington D.C.?",
            location_type="city",
            latitude=38.9072,
            longitude=-77.0369,
            difficulty="medium",
            hint="East Coast, USA",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Find Beijing, capital of China",
            location_type="city",
            latitude=39.9042,
            longitude=116.4074,
            difficulty="medium",
            hint="Northern China, hosted 2008 Olympics",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Where is Canberra, capital of Australia?",
            location_type="city",
            latitude=-35.2809,
            longitude=149.1300,
            difficulty="medium",
            hint="Southeastern Australia, not Sydney or Melbourne",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Find Ottawa, capital of Canada",
            location_type="city",
            latitude=45.4215,
            longitude=-75.6972,
            difficulty="medium",
            hint="Eastern Canada, on the Ottawa River",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Where is New Delhi, capital of India?",
            location_type="city",
            latitude=28.6139,
            longitude=77.2090,
            difficulty="medium",
            hint="Northern India, part of Delhi metropolitan area",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Find Cairo, capital of Egypt",
            location_type="city",
            latitude=30.0444,
            longitude=31.2357,
            difficulty="medium",
            hint="Northeastern Africa, on the Nile River",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Where is Buenos Aires, capital of Argentina?",
            location_type="city",
            latitude=-34.6037,
            longitude=-58.3816,
            difficulty="medium",
            hint="Eastern South America, on the Rio de la Plata",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Find Seoul, capital of South Korea",
            location_type="city",
            latitude=37.5665,
            longitude=126.9780,
            difficulty="medium",
            hint="East Asia, north of the Han River",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Where is Bangkok, capital of Thailand?",
            location_type="city",
            latitude=13.7563,
            longitude=100.5018,
            difficulty="medium",
            hint="Southeast Asia, on the Chao Phraya River",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Find Istanbul, largest city of Turkey (note: capital is Ankara)",
            location_type="city",
            latitude=41.0082,
            longitude=28.9784,
            difficulty="medium",
            hint="Straddles Europe and Asia",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Where is Ankara, capital of Turkey?",
            location_type="city",
            latitude=39.9334,
            longitude=32.8597,
            difficulty="medium",
            hint="Central Anatolia, central Turkey",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Find Jakarta, capital of Indonesia",
            location_type="city",
            latitude=-6.2088,
            longitude=106.8456,
            difficulty="medium",
            hint="Southeast Asia, on the island of Java",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Where is Mexico City, capital of Mexico?",
            location_type="city",
            latitude=19.4326,
            longitude=-99.1332,
            difficulty="medium",
            hint="Central Mexico, high altitude",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Find Nairobi, capital of Kenya",
            location_type="city",
            latitude=-1.2921,
            longitude=36.8219,
            difficulty="medium",
            hint="East Africa, near the equator",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Where is Riyadh, capital of Saudi Arabia?",
            location_type="city",
            latitude=24.7136,
            longitude=46.6753,
            difficulty="medium",
            hint="Central Arabian Peninsula",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Find Tehran, capital of Iran",
            location_type="city",
            latitude=35.6892,
            longitude=51.3890,
            difficulty="medium",
            hint="Northern Iran, south of the Caspian Sea",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Where is Baghdad, capital of Iraq?",
            location_type="city",
            latitude=33.3152,
            longitude=44.3661,
            difficulty="medium",
            hint="Middle East, on the Tigris River",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Find Kabul, capital of Afghanistan",
            location_type="city",
            latitude=34.5553,
            longitude=69.2075,
            difficulty="medium",
            hint="Eastern Afghanistan, Hindu Kush mountains",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Where is Hanoi, capital of Vietnam?",
            location_type="city",
            latitude=21.0285,
            longitude=105.8542,
            difficulty="medium",
            hint="Northern Vietnam, on the Red River",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Find Manila, capital of the Philippines",
            location_type="city",
            latitude=14.5995,
            longitude=120.9842,
            difficulty="medium",
            hint="Southeast Asia, on Luzon island",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Where is Kuala Lumpur, capital of Malaysia?",
            location_type="city",
            latitude=3.1390,
            longitude=101.6869,
            difficulty="medium",
            hint="Southeast Asia, famous for Petronas Towers",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Find Singapore, capital city-state",
            location_type="city",
            latitude=1.3521,
            longitude=103.8198,
            difficulty="medium",
            hint="Southeast Asia, island city-state",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Where is Dublin, capital of Ireland?",
            location_type="city",
            latitude=53.3498,
            longitude=-6.2603,
            difficulty="medium",
            hint="Eastern Ireland, on the Irish Sea",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Find Lisbon, capital of Portugal",
            location_type="city",
            latitude=38.7223,
            longitude=-9.1393,
            difficulty="medium",
            hint="Southwestern Europe, on the Atlantic coast",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Where is Brussels, capital of Belgium?",
            location_type="city",
            latitude=50.8503,
            longitude=4.3517,
            difficulty="medium",
            hint="Western Europe, headquarters of the EU",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Find Amsterdam, capital of the Netherlands",
            location_type="city",
            latitude=52.3676,
            longitude=4.9041,
            difficulty="medium",
            hint="Western Europe, famous for canals",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Where is Vienna, capital of Austria?",
            location_type="city",
            latitude=48.2082,
            longitude=16.3738,
            difficulty="medium",
            hint="Central Europe, on the Danube River",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Find Warsaw, capital of Poland",
            location_type="city",
            latitude=52.2297,
            longitude=21.0122,
            difficulty="medium",
            hint="Central Europe, on the Vistula River",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Where is Prague, capital of Czech Republic?",
            location_type="city",
            latitude=50.0755,
            longitude=14.4378,
            difficulty="medium",
            hint="Central Europe, City of a Hundred Spires",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Find Budapest, capital of Hungary",
            location_type="city",
            latitude=47.4979,
            longitude=19.0402,
            difficulty="medium",
            hint="Central Europe, on the Danube River",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Where is Bucharest, capital of Romania?",
            location_type="city",
            latitude=44.4268,
            longitude=26.1025,
            difficulty="medium",
            hint="Eastern Europe, south of the Carpathian Mountains",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Find Athens, capital of Greece",
            location_type="city",
            latitude=37.9838,
            longitude=23.7275,
            difficulty="medium",
            hint="Southern Europe, ancient city-state",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Where is Oslo, capital of Norway?",
            location_type="city",
            latitude=59.9139,
            longitude=10.7522,
            difficulty="medium",
            hint="Scandinavia, on the Oslofjord",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Find Stockholm, capital of Sweden",
            location_type="city",
            latitude=59.3293,
            longitude=18.0686,
            difficulty="medium",
            hint="Scandinavia, built on 14 islands",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Where is Copenhagen, capital of Denmark?",
            location_type="city",
            latitude=55.6761,
            longitude=12.5683,
            difficulty="medium",
            hint="Scandinavia, on the island of Zealand",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Find Helsinki, capital of Finland",
            location_type="city",
            latitude=60.1699,
            longitude=24.9384,
            difficulty="medium",
            hint="Northern Europe, on the Gulf of Finland",
            time_limit=45,
            category="capitals",
        ),
        Question(
            text="Where is Reykjavik, capital of Iceland?",
            location_type="city",
            latitude=64.1466,
            longitude=-21.9426,
            difficulty="medium",
            hint="North Atlantic, northernmost capital",
            time_limit=45,
            category="capitals",
        ),
        # === CAPITALS - HARD ===
        Question(
            text="Find Ulaanbaatar, capital of Mongolia",
            location_type="city",
            latitude=47.8864,
            longitude=106.9057,
            difficulty="hard",
            hint="East Asia, landlocked between Russia and China",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Wellington, capital of New Zealand?",
            location_type="city",
            latitude=-41.2865,
            longitude=174.7762,
            difficulty="hard",
            hint="Southern tip of North Island",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find Kathmandu, capital of Nepal",
            location_type="city",
            latitude=27.7172,
            longitude=85.3240,
            difficulty="hard",
            hint="Himalayan foothills",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Thimphu, capital of Bhutan?",
            location_type="city",
            latitude=27.4728,
            longitude=89.6390,
            difficulty="hard",
            hint="Himalayan kingdom, between India and China",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find Dhaka, capital of Bangladesh",
            location_type="city",
            latitude=23.8103,
            longitude=90.4125,
            difficulty="hard",
            hint="South Asia, on the Ganges Delta",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Colombo, capital of Sri Lanka?",
            location_type="city",
            latitude=6.9271,
            longitude=79.8612,
            difficulty="hard",
            hint="Indian Ocean island nation",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find Islamabad, capital of Pakistan",
            location_type="city",
            latitude=33.6844,
            longitude=73.0479,
            difficulty="hard",
            hint="Northern Pakistan, near the Himalayas",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Tashkent, capital of Uzbekistan?",
            location_type="city",
            latitude=41.2995,
            longitude=69.2401,
            difficulty="hard",
            hint="Central Asia, Silk Road city",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find Astana, capital of Kazakhstan",
            location_type="city",
            latitude=51.1694,
            longitude=71.4491,
            difficulty="hard",
            hint="Central Asia, formerly Nur-Sultan",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Bishkek, capital of Kyrgyzstan?",
            location_type="city",
            latitude=42.8746,
            longitude=74.5698,
            difficulty="hard",
            hint="Central Asia, Tian Shan mountains",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find Dushanbe, capital of Tajikistan",
            location_type="city",
            latitude=38.5598,
            longitude=68.7740,
            difficulty="hard",
            hint="Central Asia, means 'Monday' in Tajik",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Ashgabat, capital of Turkmenistan?",
            location_type="city",
            latitude=37.9601,
            longitude=58.3261,
            difficulty="hard",
            hint="Central Asia, near the Karakum Desert",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find Yerevan, capital of Armenia",
            location_type="city",
            latitude=40.1792,
            longitude=44.4991,
            difficulty="hard",
            hint="South Caucasus, one of oldest continuously inhabited cities",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Baku, capital of Azerbaijan?",
            location_type="city",
            latitude=40.4093,
            longitude=49.8671,
            difficulty="hard",
            hint="Caspian Sea coast, City of Winds",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find Tbilisi, capital of Georgia",
            location_type="city",
            latitude=41.7151,
            longitude=44.8271,
            difficulty="hard",
            hint="South Caucasus, on the Kura River",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Addis Ababa, capital of Ethiopia?",
            location_type="city",
            latitude=9.0320,
            longitude=38.7469,
            difficulty="hard",
            hint="Horn of Africa, headquarters of the African Union",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find Dar es Salaam, largest city of Tanzania (capital: Dodoma)",
            location_type="city",
            latitude=-6.7924,
            longitude=39.2083,
            difficulty="hard",
            hint="East African coast, Indian Ocean",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Kampala, capital of Uganda?",
            location_type="city",
            latitude=0.3476,
            longitude=32.5825,
            difficulty="hard",
            hint="East Africa, near Lake Victoria",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find Kigali, capital of Rwanda",
            location_type="city",
            latitude=-1.9441,
            longitude=30.0619,
            difficulty="hard",
            hint="Central Africa, land of a thousand hills",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Lusaka, capital of Zambia?",
            location_type="city",
            latitude=-15.3875,
            longitude=28.3228,
            difficulty="hard",
            hint="Southern Africa, copper-rich region",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find Harare, capital of Zimbabwe",
            location_type="city",
            latitude=-17.8252,
            longitude=31.0335,
            difficulty="hard",
            hint="Southern Africa, formerly Salisbury",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Maputo, capital of Mozambique?",
            location_type="city",
            latitude=-25.9692,
            longitude=32.5732,
            difficulty="hard",
            hint="Southeastern Africa, Indian Ocean coast",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find Antananarivo, capital of Madagascar",
            location_type="city",
            latitude=-18.8792,
            longitude=47.5079,
            difficulty="hard",
            hint="Indian Ocean island, often called Tana",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Port Louis, capital of Mauritius?",
            location_type="city",
            latitude=-20.1619,
            longitude=57.5012,
            difficulty="hard",
            hint="Indian Ocean island nation",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find Rabat, capital of Morocco",
            location_type="city",
            latitude=34.0209,
            longitude=-6.8416,
            difficulty="hard",
            hint="Northwestern Africa, Atlantic coast",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Algiers, capital of Algeria?",
            location_type="city",
            latitude=36.7538,
            longitude=3.0588,
            difficulty="hard",
            hint="North Africa, Mediterranean coast",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find Tunis, capital of Tunisia",
            location_type="city",
            latitude=36.8065,
            longitude=10.1815,
            difficulty="hard",
            hint="North Africa, near ancient Carthage",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Tripoli, capital of Libya?",
            location_type="city",
            latitude=32.8872,
            longitude=13.1913,
            difficulty="hard",
            hint="North Africa, Mediterranean coast",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find Khartoum, capital of Sudan",
            location_type="city",
            latitude=15.5007,
            longitude=32.5599,
            difficulty="hard",
            hint="Northeastern Africa, at the confluence of the Niles",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Lima, capital of Peru?",
            location_type="city",
            latitude=-12.0464,
            longitude=-77.0428,
            difficulty="hard",
            hint="Western South America, Pacific coast",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find La Paz, administrative capital of Bolivia",
            location_type="city",
            latitude=-16.5000,
            longitude=-68.1500,
            difficulty="hard",
            hint="Highest capital city in the world",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Quito, capital of Ecuador?",
            location_type="city",
            latitude=-0.1807,
            longitude=-78.4678,
            difficulty="hard",
            hint="Andes Mountains, closest capital to the equator",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find Caracas, capital of Venezuela",
            location_type="city",
            latitude=10.4806,
            longitude=-66.9036,
            difficulty="hard",
            hint="Northern South America, Caribbean coast",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Bogota, capital of Colombia?",
            location_type="city",
            latitude=4.7110,
            longitude=-74.0721,
            difficulty="hard",
            hint="Andes Mountains, high altitude",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find Santiago, capital of Chile",
            location_type="city",
            latitude=-33.4489,
            longitude=-70.6693,
            difficulty="hard",
            hint="Western South America, Andes foothills",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Asuncion, capital of Paraguay?",
            location_type="city",
            latitude=-25.2637,
            longitude=-57.5759,
            difficulty="hard",
            hint="South America, on the Paraguay River",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find Montevideo, capital of Uruguay",
            location_type="city",
            latitude=-34.9011,
            longitude=-56.1645,
            difficulty="hard",
            hint="Southern South America, Rio de la Plata coast",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Georgetown, capital of Guyana?",
            location_type="city",
            latitude=6.8013,
            longitude=-58.1551,
            difficulty="hard",
            hint="Northern South America, Caribbean coast",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find Paramaribo, capital of Suriname",
            location_type="city",
            latitude=5.8520,
            longitude=-55.2038,
            difficulty="hard",
            hint="Northern South America, smallest independent country in Americas",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Kingston, capital of Jamaica?",
            location_type="city",
            latitude=17.9714,
            longitude=-76.7931,
            difficulty="hard",
            hint="Caribbean island, natural harbor",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find Havana, capital of Cuba",
            location_type="city",
            latitude=23.1136,
            longitude=-82.3666,
            difficulty="hard",
            hint="Caribbean, Gulf of Mexico",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Port-au-Prince, capital of Haiti?",
            location_type="city",
            latitude=18.5944,
            longitude=-72.3074,
            difficulty="hard",
            hint="Caribbean, Hispaniola island",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find Santo Domingo, capital of Dominican Republic",
            location_type="city",
            latitude=18.4861,
            longitude=-69.9312,
            difficulty="hard",
            hint="Caribbean, oldest European settlement in Americas",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is San Jose, capital of Costa Rica?",
            location_type="city",
            latitude=9.9281,
            longitude=-84.0907,
            difficulty="hard",
            hint="Central America, mountainous valley",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find Panama City, capital of Panama",
            location_type="city",
            latitude=8.9824,
            longitude=-79.5199,
            difficulty="hard",
            hint="Central America, Pacific entrance to the canal",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Guatemala City, capital of Guatemala?",
            location_type="city",
            latitude=14.6349,
            longitude=-90.5069,
            difficulty="hard",
            hint="Central America, largest city in Central America",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find San Salvador, capital of El Salvador",
            location_type="city",
            latitude=13.6929,
            longitude=-89.2182,
            difficulty="hard",
            hint="Central America, Pacific coast region",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Tegucigalpa, capital of Honduras?",
            location_type="city",
            latitude=14.0723,
            longitude=-87.1921,
            difficulty="hard",
            hint="Central America, mountainous interior",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Find Managua, capital of Nicaragua",
            location_type="city",
            latitude=12.1150,
            longitude=-86.2362,
            difficulty="hard",
            hint="Central America, on Lake Managua",
            time_limit=30,
            category="capitals",
        ),
        Question(
            text="Where is Belmopan, capital of Belize?",
            location_type="city",
            latitude=17.2510,
            longitude=-88.7590,
            difficulty="hard",
            hint="Central America, inland from Caribbean",
            time_limit=30,
            category="capitals",
        ),
    ]

    db = SessionLocal()
    try:
        from sqlalchemy import select

        # Check if questions exist and if they have categories
        stmt = select(Question)
        try:
            all_questions = db.execute(stmt).scalars().all()
        except Exception as e:
            logger.warning("questions_table_not_ready", error=str(e))
            all_questions = []

        if len(all_questions) > 0:
            # Check if any questions have null category
            questions_without_category = sum(1 for q in all_questions if q.category is None)

            if questions_without_category > 0:
                logger.info("questions_without_category_found", count=questions_without_category)
                db.query(Question).delete()
                db.commit()
                # Continue to seed fresh
            else:
                logger.info("questions_already_seeded")
                return

        # Seed questions
        db.add_all(sample_questions)
        db.commit()
        logger.info("questions_seeded", count=len(sample_questions))

        # Log all questions with their categories for debugging
        questions = db.query(Question).all()
        logger.debug("question_categories_in_database")
        for q in questions:
            text_preview = q.text[:30].replace("\n", " ")
            logger.debug(
                "question_entry",
                id=q.id,
                category=q.category or "None",
                text=text_preview,
            )
    finally:
        db.close()
